In [3]:
import numpy as np
import math
def sigmoid(z):
    sgm = 1/(1+math.exp(-z))
    return sgm

In [5]:
sigmoid(4.6)

0.9900481981330957

In [6]:
def sigmoid_numpy(z):
    sgm = 1/(1+np.exp(-z))
    return sgm

In [7]:
z = np.array([1,2,3])

In [8]:
sigmoid_numpy(z)

array([0.73105858, 0.88079708, 0.95257413])

In [9]:
def sigmoid_der(z):
    sgm = 1/(1+np.exp(-z))
    sgm_der = sgm*(1-sgm)
    return sgm_der

In [10]:
sigmoid_der(z)

array([0.19661193, 0.10499359, 0.04517666])

In [11]:
image = np.random.rand(3,3,3)

In [13]:
print(image)

[[[0.83995672 0.45300499 0.91475652]
  [0.29701151 0.79447265 0.49219304]
  [0.46433678 0.43791231 0.81256496]]

 [[0.88701639 0.84191775 0.08790715]
  [0.53430646 0.0231113  0.7385702 ]
  [0.71452225 0.29332369 0.77537762]]

 [[0.66450608 0.81375227 0.39164606]
  [0.38389162 0.80026463 0.89060619]
  [0.20451001 0.03959666 0.9011313 ]]]


In [18]:
length = image.shape[0]
height = image.shape[1]
height, length

(3, 3)

In [19]:
image = np.reshape(image,(length*height*3,1))

In [21]:
image.shape

(27, 1)

In [39]:
x = np.array([[0,3,4],[1,6,4]])

In [40]:
x

array([[0, 3, 4],
       [1, 6, 4]])

In [41]:
norm = np.linalg.norm(x,axis=1,keepdims=True)

In [42]:
norm

array([[5.        ],
       [7.28010989]])

In [43]:
normalized = np.divide(x,norm)

In [44]:
normalized

array([[0.        , 0.6       , 0.8       ],
       [0.13736056, 0.82416338, 0.54944226]])

In [45]:
def normalizer(x):
    norm = np.linalg.norm(x,axis=1,keepdims=True)
    normalized = np.divide(x,norm)
    return normalized

**Instructions**:
- $ \text{for } x \in \mathbb{R}^{1\times n} \text{,     } softmax(x) = softmax(\begin{bmatrix}
    x_1  &&
    x_2 &&
    ...  &&
    x_n  
\end{bmatrix}) = \begin{bmatrix}
     \frac{e^{x_1}}{\sum_{j}e^{x_j}}  &&
    \frac{e^{x_2}}{\sum_{j}e^{x_j}}  &&
    ...  &&
    \frac{e^{x_n}}{\sum_{j}e^{x_j}} 
\end{bmatrix} $ 


- $\text{for a matrix } x \in \mathbb{R}^{m \times n} \text{,  $x_{ij}$ maps to the element in the $i^{th}$ row and $j^{th}$ column of $x$, thus we have: }$  $$softmax(x) = softmax\begin{bmatrix}
    x_{11} & x_{12} & x_{13} & \dots  & x_{1n} \\
    x_{21} & x_{22} & x_{23} & \dots  & x_{2n} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    x_{m1} & x_{m2} & x_{m3} & \dots  & x_{mn}
\end{bmatrix} = \begin{bmatrix}
    \frac{e^{x_{11}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{12}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{13}}}{\sum_{j}e^{x_{1j}}} & \dots  & \frac{e^{x_{1n}}}{\sum_{j}e^{x_{1j}}} \\
    \frac{e^{x_{21}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{22}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{23}}}{\sum_{j}e^{x_{2j}}} & \dots  & \frac{e^{x_{2n}}}{\sum_{j}e^{x_{2j}}} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    \frac{e^{x_{m1}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m2}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m3}}}{\sum_{j}e^{x_{mj}}} & \dots  & \frac{e^{x_{mn}}}{\sum_{j}e^{x_{mj}}}
\end{bmatrix} = \begin{pmatrix}
    softmax\text{(first row of x)}  \\
    softmax\text{(second row of x)} \\
    ...  \\
    softmax\text{(last row of x)} \\
\end{pmatrix} $$

In [46]:
x = np.array([[1,2,3],[5,6,7]])

In [47]:
x_exp = np.exp(x)

In [48]:
x_exp

array([[   2.71828183,    7.3890561 ,   20.08553692],
       [ 148.4131591 ,  403.42879349, 1096.63315843]])

In [52]:
def softmax(x):
    x_exp = np.exp(x)
    norm = np.sum(x_exp,axis=1,keepdims=True)
    soft = x_exp/norm
    return soft

In [53]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])

In [54]:
softmax(x)

array([[9.80897665e-01, 8.94462891e-04, 1.79657674e-02, 1.21052389e-04,
        1.21052389e-04],
       [8.78679856e-01, 1.18916387e-01, 8.01252314e-04, 8.01252314e-04,
        8.01252314e-04]])

In [68]:
y = np.random.rand(2,2)*10
y_head = np.random.rand(2,2)*10

In [69]:
y, y_head

(array([[1.42672668, 6.01499079],
        [9.8745753 , 4.38394657]]),
 array([[8.15831565, 7.51210404],
        [1.21255745, 0.713012  ]]))

In [70]:
print(abs(y_head-y))

[[6.73158897 1.49711324]
 [8.66201784 3.67093457]]


In [77]:
L1 = sum(abs(y_head-y))

In [78]:
L1

1.1

In [79]:
def losfunction(y_head,y):
    L1 = np.sum(abs(y_head-y))
    return L1

In [80]:
y_head = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])

In [81]:
losfunction(y_head,y)

1.1

In [83]:
def losfunction2(y_head,y):
    L2 = np.sum(abs(y_head-y)**2)
    return L2

In [84]:
losfunction2(y_head,y)

0.43