In [17]:
import numpy as np

In [18]:
a = np.array([1,2,3,4])

In [19]:
a

array([1, 2, 3, 4])

In [22]:
import time 

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized:",str(1000*(toc-tic))+" ms")

d = 0
tic = time.time()
for i in range(1000000):
    d += a[i]*b[i]
toc = time.time()

print(d)
print("Non-Vectorized:",str(1000*(toc-tic))+" ms")

250036.77305502183
Vectorized: 0.9934902191162109 ms
250036.77305501926
Non-Vectorized: 496.6697692871094 ms


In [25]:
v = np.random.rand(20)

In [26]:
v

array([0.84292865, 0.20789888, 0.05094056, 0.99842061, 0.64678748,
       0.90093421, 0.62874791, 0.48549089, 0.36586763, 0.87778326,
       0.19125809, 0.81276818, 0.46859204, 0.49690458, 0.9324445 ,
       0.91603319, 0.57923571, 0.12118961, 0.67523325, 0.59263466])

In [27]:
v = np.exp(v)

In [28]:
v

array([2.32316075, 1.23108867, 1.05226035, 2.713992  , 1.90939699,
       2.46190196, 1.8752611 , 1.6249725 , 1.44176439, 2.40556128,
       1.2107719 , 2.25413921, 1.59774305, 1.64362567, 2.54071236,
       2.49935623, 1.78467389, 1.12883894, 1.96449115, 1.80874757])

#### Logistic Regression Vectorization

In [30]:
dw = np.zeros((10,1))

### Z = np.dot(w.transpose( ),X) + b
### A = sigmoid(Z)
### dz = A-Y
### db = (1/m)*np.sum(dz)
### dw = (1/m)*np.dot(X,dz.transpose( ))

In [51]:
A = np.array([1,2,3,4,5])

In [52]:
Y = np.array([4,6,4,3,7])

In [54]:
dz = np.subtract(A,Y)
dz

array([-3, -4, -1,  1, -2])

In [56]:
X = np.array([9,8,6,4,6])
Result = np.multiply(X,dz)
Result

array([-27, -32,  -6,   4, -12])

In [81]:
A = np.random.rand(3,4)

In [82]:
A

array([[0.13503569, 0.99138311, 0.46877112, 0.58983119],
       [0.77824986, 0.35243887, 0.43421209, 0.30046118],
       [0.15441717, 0.32713975, 0.78082592, 0.06664447]])

In [83]:
cal = A.sum(axis = 0)
cal

array([1.06770272, 1.67096173, 1.68380912, 0.95693684])

In [84]:
Per = np.divide(A,cal)*100

In [85]:
Per

array([[12.64731157, 59.33009055, 27.8399203 , 61.63742119],
       [72.89012586, 21.09197761, 25.78748879, 31.39822475],
       [14.46256257, 19.57793184, 46.37259091,  6.96435405]])